### ISSUE TITLE
Bind multiple functions on ($click)

### ISSUE THREAD

**Issue by arti1793** [canjs/can-stache-bindings#115]
It'd be more comfortable to use `func(arg);func2(arg2);`

**Comment by justinbmeyer** [comment]
This should be done after `parse` is used for expression parsing.

**Comment by christopherjbaker** [comment]
It seems that the call to `expression.parse` (or more specifically, `expression.ast`) is consuming the second call in `($click)='do1(1); do2(2);'` (with commas or semicolons). Would it be better to modify the expression parser to see both of these, or to split the value and [parse multiple expressions](https://github.com/canjs/can-stache-bindings/blob/fbe577da79eaff612d1796d0eb121373e98e20e6/can-stache-bindings.js#L274)?

I think the first option would be more work and have further reaching effects, but possibly more useful. In the second case, what is the significance of the [return value](https://github.com/canjs/can-stache-bindings/blob/fbe577da79eaff612d1796d0eb121373e98e20e6/can-stache-bindings.js#L326), and what would be the best way to extend this over multiple values? It appears to just be the return value of the function itself, so just an array of values?

**Comment by christopherjbaker** [comment]
closing for canjs/can-parse#6
