### ISSUE TITLE
remove legacy mustache 

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-stache-bindings#121]
in mustache the `@` operator is used for `Using attribute values` in components (see https://v2.canjs.com/2.1/docs/can.Component.prototype.scope.html -> Using attribute values)

since this lines are removed in can 3.0 https://github.com/canjs/canjs/blob/2.3-legacy/component/component.js#L60-L65
we dont need these test https://github.com/canjs/can-stache-bindings/blob/master/test/bindings-test.js#L82-L104 and also can remove some legacy code e.g. https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L682-L691 
i dont find all the stuff that handles the `@` lookup

cc @justinbmeyer

**Comment by christopherjbaker** [comment]
All of the tests that reference the legacy code are in can-component, and take the form `<my-element foo='bar' />`, which we probably can't get rid of till 4.0. We could refactor slightly to remove support for `@`, but there wouldn't be an optimization benefit, so it is probably best to leave the whole issue till then.

**Comment by justinbmeyer** [comment]
this is done in major
