### ISSUE TITLE
Solve issue with two way binding values that become unequal

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#122]
This issue was prompted by http://forums.donejs.com/t/strange-behaviour-map-define-set/534 and from similar functionality encountered while building Bitcentive.

In short, a two way binding can have values that are unequal.  This is confusing and we need a solution.

##  The Problem

If someone creates a template like:

```html
<input {($value)}="firstName"/>
```

And has a viewModel like:

```js
ViewModel = DefineMap.extend({
  set firstName(newValue){ 
    return newValue.toLowerCase()
  }
})
```

The `input`'s `.value` and the `ViewModel`'s `.firstName` can get out of sync in the following scenario:

1.  The user types `matthew` and clicks away, causing a _change_ event.
2.  The user replaces `matthew` with  `MATTHEW` and clicks away, causing a _change_ event.

The `input`'s value will remain `"MATTHEW"` while the `viewModel.firstName` will be `"matthew"`.

## The cause 

This happens because in a binding like `{($value)}="firstName"`, `input.value` is only updated when `viewModel.firstName` changes, and vice-versa.  

1. The `viewModel.firstName` is `"matthew"` at the start of step `#2` above.
2. When the user updates the `input.value` to `"MATTHEW"`, this fires a change event that sets `viewModel.firstName = "MATTHEW"`
3.  That `set` doesn't actually cause a change in the `viewModel`.  So no event is fired, so the DOM never updates back to `matthew`.

### Sticky 

We could make two-way bindings sticky with respect to the `parent` value.  So consider the following:

- `<my-component {(child)}="parentA"/>`
- `<input {($value)}="parentB"/>`

If `child` changes, it will update `parentA`.  Once the batch is complete, it will try to set `child` to `parentA` again.  Any other changes to `child` will be ignored from this point forward to prevent recursion.

If `value` changes, it will update `parentB`.  Once the batch is complete, it will try to set `value` to `parentB` again.  Any other changes to `child` will be ignored from this point forward to prevent recursion.

Pros:

 - if this makes sense everywhere ... great!

Cons:

 - needs to be tested to make sure it doesn't break other use cases 
 - arguably a breaking change

### Syntax

We support some type of syntax to specify which part of the binding is dominate.  For example (but not suggesting):

- `<my-component {(child="parentA"/>`  - `parentA`'s value is sticky to `child`.
- `<input $value)}="parentB"/>` - `.value` is sticky to `parentB`.

Pros:
 - no breaking change
 - fine grained control over behavior

Cons:
 - more syntax, are you kidding me?

## Other considerations

Who wins with sibling components?

```
<driver-list {(*selected-plate)}="*plateName"/>
<edit-plate {(plate)}="*plateName"/>
```

`*plateName` would dominate ... but as that causes an update in the sibling component, what should be the actual behavior.   Consider what if `<driver-list>` converts plates to numbers and `edit-plate` to strings.  #114

**Comment by DesignByOnyx** [comment]
This explanation is good. Just wanted to clarify **The Cause** a little bit.

The viewModel listens for property value changes and updates the view only when a change actually happens. In the example above the `firstName` setter converts all values to lowercase. Therefore, if the user tries to change the value from "matthew" to "Matthew" to "MATTHEW" to "mAtTheW" - all are converted to "matthew" . The viewModel never notices that anything changes and the view is never updated. The user sees the last value he entered ("mAtTheW") yet `viewModel.firstName === "matthew"`.

**Comment by matthewp** [comment]
I think sticky is the way to go. Forcing a syntax puts a big cognitive burden on the user. I can't imagine needing this and *not* thinking it was just a bug.

**Comment by phillipskevin** [comment]
I think that sticky is the way to go too since I think that is what most people would expect. Also:

> more syntax, are you kidding me?

Trying to explain the need for that syntax alone would make it totally not worthwhile.

I'm curious if there are any use cases that would have unexpected behavior if the sticky option was turned on. @justinbmeyer you mentioned it might just be a matter of flipping this flag, right? https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L503. A good first step might be for someone to try changing the default of that flag and running through all of the canjs/canjs tests to see what happens.

**Comment by justinbmeyer** [comment]
I just tested it.  It actually wasn't the sticky option, it was the `syncChildWithParent`.  Setting it to true keeps all `can-stache-bindings` tests working.

**Comment by justinbmeyer** [comment]
All tests pass.  So ... is this a breaking change?

**Comment by justinbmeyer** [comment]
I can confirm this is how `can-value` worked.  So maybe this has been a bug all along.

**Comment by matthewp** [comment]
I don't see this as a breaking change.
