### ISSUE TITLE
($event) inside {{#if}} not working if POJO view model is used

### ISSUE THREAD

**Issue by nlundquist** [canjs/can-stache-bindings#134]
For whatever reason an $(event) binding used inside an {{#if}} doesn't work if the model is a POJO:
ex.) https://jsbin.com/ziqepitiyu/3/edit?html,js,console,output

However everything works as expected if the model is a can.Map or DefineMap:
ex.) https://jsbin.com/poxeyeleko/edit?html,js,console,output

**Comment by Macrofig** [comment]
Updated the example to latest canjs release (3.10.3) and example works as expected. https://jsbin.com/sibevex/edit?html,js,console,output
