### ISSUE TITLE
The checked binding for undefined checks a checkbox

### ISSUE THREAD

**Issue by ilyavf** [canjs/can-stache-bindings#135]
For one-way binding with undefined property value:

```
<input type="checkbox" {$checked}="user.isAdmin" />
```

For `user.isAdmin === undefined` checks the checkbox.

**Comment by justinbmeyer** [comment]
@ilyavf I assume this is fixed?  Please advise.

**Comment by christopherjbaker** [comment]
Yes, this was previously fixed by canjs/can-util#188. Created a PR for @ilyavf s test at canjs/can-stache-bindings#182 to prevent regressions.
