### ISSUE TITLE
Better warning when a binding can't set a value`

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#136]
From http://forums.donejs.com/t/data-binding-multi-select-with-data-transformed/554/2

We should let people know when they are trying to set a value on something that doesn't exist.

**Comment by justinbmeyer** [comment]
If a binding is set on a property that doesn't exist we should warn.  Typically this will only happen with deep properties like:

```
<input {value}="foo.bar"/>
```

**Comment by christopherjbaker** [comment]
I'm having some trouble figuring out where to put this. Some direction here would be helpful I think, or somebody else can run with it. =]

**Comment by justinbmeyer** [comment]
Somewhere scope.get or scope.attr or scope.computeData ... well somewhere the scope is read.  If computeData is used we can know if a value wasn't found, we do this in can-stache and warn. We need to do something similar. Look for 'scope:' to find the part where scope bindings are setup
