### ISSUE TITLE
get rid of calling .attr()

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#140]
![cursor_and_js_bin_-_collaborative_javascript_debugging](https://cloud.githubusercontent.com/assets/78602/23633269/b5c2ed06-028a-11e7-8105-1084391279fb.png)

**Comment by phillipskevin** [comment]
This should be closed by https://github.com/canjs/can-stache-bindings/pull/154, which was merged but needs to be released.

**Comment by phillipskevin** [comment]
This is closed by https://github.com/canjs/can-stache-bindings/releases/tag/v3.0.13.
