### ISSUE TITLE
can-event test fails intermittently in canjs test suite

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#146]
[This test](https://github.com/canjs/can-stache-bindings/blob/master/test/bindings-test.js#L889-L908) fails intermittently in the canjs test suite because the event is triggered after the DOM is switched between the real DOM and virtual DOM.

![image](https://cloud.githubusercontent.com/assets/5851984/23722735/19ccb00c-040c-11e7-8d0c-48c81c7d89dc.png)

**Comment by justinbmeyer** [comment]
cc @bmomberger-bitovi related to #76
