### ISSUE TITLE
Test failing in IE9

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#150]
This test failed in Sauce Labs in the canjs test suite:
![image](https://cloud.githubusercontent.com/assets/5851984/23812809/b2f22992-05a1-11e7-9a87-c5d271121075.png)

**Comment by christopherjbaker** [comment]
Like canjs/can-compute#64, I ran this whole suite in IE9 in both BrowserStack and SauceLabs with no issues.
