### ISSUE TITLE
can.view.bindings API page is broken

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#163]
@prashantsharmain commented on [Mon Sep 19 2016](https://github.com/canjs/canjs/issues/2500)

Multiple issues seen on [can.view.bindings](https://canjs.com/docs/can.view.bindings.event.html) API page:
1. ($DOM_EVENT)='CALL_EXPRESSION' anchor link is broken
2. (VIEW_MODEL_EVENT)='CALL_EXPRESSION' anchor link is broken
3. Parameters section of (VIEW_MODEL_EVENT)='CALL_EXPRESSION' incorrectly lists **DOM_EVENT** as the first parameter: _DOM_EVENT {String} A DOM event name like "click". jQuery custom events can also be given_. Description should be updated to state it's a **VIEW_MODEL_EVENT** and not a **DOM_EVENT**

**Comment by justinbmeyer** [comment]
Lets make sure this looks ok for 3.0. http://canjs.com/doc/can-stache-bindings.html

**Comment by andrejewski** [comment]
Fixed by #169
