### ISSUE TITLE
($event) for custom DOM events doesn't end up attaching a listener

### ISSUE THREAD

**Issue by nlundquist** [canjs/can-stache-bindings#188]
In Can 2.3 custom DOM events could be attached with `($custom-event)="myEventHandler(...)"`. 

This can be seen in this JSBin: http://jsbin.com/nocexecugi/1/edit?html,console,output
Which we can confirm a listener for `customEvent` is attached to the div via the Chrome Dev Tools:
![screen shot 2017-04-25 at 10 50 11 am](https://cloud.githubusercontent.com/assets/2623867/25397299/10d4194a-29a5-11e7-959d-25492bceec81.png)

However in Can 3.x custom DOM events do not attach as expected as seen in this JSBin with essentially identical code: http://jsbin.com/pimoheduga/1/edit?html,console,output
We can confirm a listener is not attached via the dev tools:
![screen shot 2017-04-25 at 10 54 47 am](https://cloud.githubusercontent.com/assets/2623867/25397504/b26a4f90-29a5-11e7-9672-43f1fc1badd1.png)

**Comment by nlundquist** [comment]
This inconsistency between 2.3 & 3.x is partially resolved by adding `\-` to the event binding regex in can-stache-bindings.js . However this creates a listener for `custom-event` instead of `customEvent` as expected.

**Comment by nlundquist** [comment]
This issue will be resolved by implementing [can-stache#194](https://github.com/canjs/can-stache/issues/194)

**Comment by phillipskevin** [comment]
This is possible with the new binding syntax.
