### ISSUE TITLE
Checkout forced `undefined` setting

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#189]
Reported by @rjgotten on https://github.com/canjs/can-stache-bindings/pull/123#issuecomment-295176774

=============

@justinbmeyer 
I ported these changes to my local build of CanJS 2.3.28 and there I notice that a two-way binding on a component to a non-existent property on the outer / parent scope, now always forces a sync of the child end of the binding with the value `undefined`. 

E.g. given a component

```js
can.Component.extend({
  tag : "test-component",
  viewModel : {
    define : { "value" : { type : "boolean", value : false }},
    toggle : function() { this.attr( "value", !this.attr( "value" )) }
  },
  template : can.stache( '<button type="button" ($click)="toggle()">{{value}}</button>' )
});
```

When rendered when two-way binding the `value` property to a non-existent property on the parent scope, e.g.

```html
<test-component {(value)}="./does-not-exist" />
```

then it will always force a child sync with `undefined`, which will coerce back to `false`.

Not sure if this issue would also replicate in CanJS 3.x but the internals of the binding mechanism match close enough that I think it would. Probably you want some type of special handling here to ignore child syncs for a non-existent parent end of the binding.

**Comment by justinbmeyer** [comment]
@rjgotten Are you saying that if you didn't have `type: "boolean"`, `test-component`'s viewModel's `value` property would be `undefined`?

**Comment by justinbmeyer** [comment]
@rjgotten, what do you think the behavior should be?  Should we treat `undefined` as a special case?  That because we can not set `does-not-exist`, we keep the child value?  What is the scope in 

```
<test-component {(value)}="./does-not-exist" /> 
```

? A plain JS object?  Can you create a JSBin?  Thanks!

**Comment by andrejewski** [comment]
JSBin (using DefineMap): http://jsbin.com/kuyaqocuci/1/edit?html,js,output

This JSBin is using the latest Can. My JSBin toggles false/true as I think is expected by @rjgotten. If you replace `s/DefineMap/Map` and `s/.get/.attr` and `s/.set/.attr/` it also works in the same way.

**Comment by justinbmeyer** [comment]
@andrejewski I'm not sure what you mean by "what @rjgotten expects" (ex: if he is expecting broken or working behavior).

To clarify, would you say that the JSBin behaves the way a developer would expect?

Also, this is using latest CanJS, but not the "sticky" bindings that were finally merged to master.  Can you try this (maybe create a test), and see if this example still behaves the right way?  Thanks!

**Comment by andrejewski** [comment]
I assumed the develop would expect the component to work when the property is undefined. My reasoning was otherwise why did they make the issue *("How dare this be working?")* but I could be wrong so we can wait for clarification. The JSBin works how I would expect.

I can make a test; could you elaborate on these "sticky bindings" or is the change documented somewhere?

**Comment by rjgotten** [comment]
> Should we treat undefined as a special case? That because we can not set `does-not-exist`, we keep the child value? 
>
> What is the scope in [...] ? A plain JS object?

@justinbmeyer , exactly that.
Given a binding defined between a property on a child view model and a property on a parent scope, and given the fact that the property on the parent doesn't actually exist in a settable form, I would reasonably expect a child->parent update to be a no-op and I would not expect the non-existent end of the binding to reciprocate with an `undefined` value.

The scope was a plain JS object, yes.

**Comment by rjgotten** [comment]
@andrejewski 
Nice to see the explicit unit test. I assume it already passes in CanJS 3.x and what I was seeing was merely an artifact of applying the same patch to 2.3.28 ?
