### ISSUE TITLE
{$focused} is not working

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-stache-bindings#196]
this simple exmaple shows, that the input will not be focused.
https://jsbin.com/mitikugaqi/edit?html,js,console,output

it should be working as described in the docs.
https://canjs.com/doc/can-util/dom/attr/attr.special.focused.html

there is a test https://github.com/canjs/can-stache-bindings/blob/master/test/bindings-define-test.js#L208 that pass, dont know why...

@justinbmeyer any idea?

**Comment by justinbmeyer** [comment]
Have you done this outside a jsbin? It does odd things with focus.

**Comment by bmomberger-bitovi** [comment]
Here it is as a glitch, showing the same issue.  https://glitch.com/edit/#!/heather-capricorn

Also, this is a problem with can-util's DOM attributes library, not with stache bindings, so closing in favor of an issue there: https://github.com/canjs/can-util/issues/263
