### ISSUE TITLE
Decode `\s` in an attribute name

### ISSUE THREAD

**Issue by mickmcgrath13** [canjs/can-stache-bindings#197]
can-view-parser is encoding a `\s` when there are spaces in an attribute name (https://github.com/canjs/can-view-parser/pull/50).
Ex:
```
<my-component {.\ssomeProp} />
```

Can stache bindings needs to decode the `\s` to get `{. someProp}` and then set up bindings appropriately based on the two parts of the string.  The left side (before the space) will be a sort of context for the binding similar to can-control's event delegation syntax (ex: `"{viewModel} someProp": function(el,ev){}`).

The left side (before the space) can be anything accessible in the scope using things like:
* `{. someProp}`
* `{.. someProp}`
* `{../someParentScopeObject someProp}`
* etc

**Comment by mickmcgrath13** [comment]
I looked into the `getBindingInfo` method ([here](https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L689)), and it doesn't quite seem right to continue trying to fit the attribute name into the `childName` because the attribute name will not necessarily be binding to the child.  

`parentToChild` and `childToParent` would seem a little ambiguous, too because, for example, `{. someProp}="someOtherProp"` would be neither child-to-parent nor parent-to-child, right?  Wouldn't it be more along the lines of parent-to-parent?

It's not quite clear to me how to proceed; let's discuss tomorrow, @justinbmeyer

**Comment by justinbmeyer** [comment]
Child/parent is fine for now. Better might be left and right. But it's not worth changing.
