### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by mindfulmike** [canjs/can-stache-bindings#226]
https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L35

This doesn't resolve in plain cjs land. There's no mapping to this. I'm using Node 8/latest webpack.

This makes can-component also un-compilable. I think its nice that people not using steal can still have canjs.

**Comment by andrejewski** [comment]
There's a fix incoming, see https://github.com/canjs/can-stache-bindings/pull/223.

**Comment by mindfulmike** [comment]
👍
