### ISSUE TITLE
Create regexes for new binding syntax codemods

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#264]
For the codemods in https://github.com/canjs/can-stache-bindings/issues/229, it would be great to have regular expressions to use in codemods for updating all our guides / recipes.

Here is the basics of what we would need:
`($click)` -> `on:click`
`{$value}` -> `value:from`
`{^$value}` -> `value:to`
`{($value)}` -> `value:bind` <sub>James edit: this originally had `({$value})` as the 2.3 syntax, just fixed that.</sub>

**Comment by JaneOri** [comment]
<sup>note: the rows in these sets are ordered specifically so the replaces won't interfere with each other</sup>

2.3 syntax to context intuitive 3.x binding:

example input | example output | RegExp | replace string
-----|----|---------|----
`{^$value}=` or `{^value}=` | `value:to=` | `/\{\^\$?([^}\n]+)\}=/g` | `$1:to=`
`{($value)}=` or `{(value)}=` | `value:bind=` | `/\{\(\$?([^)\n]+)\)\}=/g` | `$1:bind=`
`{$value}=` or `{value}=` | `value:from=` | `/\{\$?([^}\n]+)\}=/g` | `$1:from=`
`($click)=` or `(click)=` | `on:click=` | `/\(\$?([^)\n]+)\)=/g` | `on:$1=`

-----

2.3 syntax to specific 3.x binding:

example input | example output | RegExp | replace string
-----|----|---------|----
`{^$value}=` | `el:value:to=` | `/\{\^\$([^}\n]+)\}=/g` | `el:$1:to=`
`{^value}=` | `vm:value:to=` | `/\{\^([^}\n]+)\}=/g` | `vm:$1:to=`
`{($value)}=` | `el:value:bind=` | `/\{\(\$([^)\n]+)\)\}=/g` | `el:$1:bind=`
`{(value)}=` | `vm:value:bind=` | `/\{\(([^)\n]+)\)\}=/g` | `vm:$1:bind=`
`{$value}=` | `el:value:from=` | `/\{\$([^}\n]+)\}=/g` | `el:$1:from=`
`{value}=` | `vm:value:from=` | `/\{([^}\n]+)\}=/g` | `vm:$1:from=`
`($click)=` | `el:on:click=` | `/\(\$([^)\n]+)\)=/g` | `el:on:$1=`
`(click)=` | `vm:on:click=` | `/\(([^)\n]+)\)=/g` | `vm:on:$1=`

-----

2.3 syntax to mixed* 3.x binding:
<sub>* mixed specifically to mirror 2.3 in that it binds to vm props by default and there's something extra when specifically binding to element attrs instead</sub>

example input | example output | RegExp | replace string
-----|----|---------|----
`{^$value}=` | `el:value:to=` | `/\{\^\$([^}\n]+)\}=/g` | `el:$1:to=`
`{^value}=` | `value:to=` | `/\{\^([^}\n]+)\}=/g` | `$1:to=`
`{($value)}=` | `el:value:bind=` | `/\{\(\$([^)\n]+)\)\}=/g` | `el:$1:bind=`
`{(value)}=` | `value:bind=` | `/\{\(([^)\n]+)\)\}=/g` | `$1:bind=`
`{$value}=` | `el:value:from=` | `/\{\$([^}\n]+)\}=/g` | `el:$1:from=`
`{value}=` | `value:from=` | `/\{([^}\n]+)\}=/g` | `$1:from=`
`($click)=` | `el:on:click=` | `/\(\$([^)\n]+)\)=/g` | `el:on:$1=`
`(click)=` | `on:click=` | `/\(([^)\n]+)\)=/g` | `on:$1=`


-----

Full replace scripts:

2.3 syntax to context intuitive 3.x binding:
```
template = template.replace(/\{\^\$?([^}\n]+)\}=/g, "$1:to=");
template = template.replace(/\{\(\$?([^)\n]+)\)\}=/g, "$1:bind=");
template = template.replace(/\{\$?([^}\n]+)\}=/g, "$1:from=");
template = template.replace(/\(\$?([^)\n]+)\)=/g, "on:$1=");
```

2.3 syntax to specific 3.x binding:
```
template = template.replace(/\{\^\$([^}\n]+)\}=/g, "el:$1:to=");
template = template.replace(/\{\^([^}\n]+)\}=/g, "vm:$1:to=");
template = template.replace(/\{\(\$([^)\n]+)\)\}=/g, "el:$1:bind=");
template = template.replace(/\{\(([^)\n]+)\)\}=/g, "vm:$1:bind=");
template = template.replace(/\{\$([^}\n]+)\}=/g, "el:$1:from=");
template = template.replace(/\{([^}\n]+)\}=/g, "vm:$1:from=");
template = template.replace(/\(\$([^)\n]+)\)=/g, "el:on:$1=");
template = template.replace(/\(([^)\n]+)\)=/g, "vm:on:$1=");
```

2.3 syntax to mixed* 3.x binding:
<sub>* mixed specifically to mirror 2.3 in that it binds to vm props by default and there's something extra when specifically binding to element attrs instead</sub>
```
template = template.replace(/\{\^\$([^)\n]+)\}=/g, "el:$1:to=");
template = template.replace(/\{\^([^)\n]+)\}=/g, "$1:to=");
template = template.replace(/\{\(\$([^)\n]+)\)\}=/g, "el:$1:bind=");
template = template.replace(/\{\(([^)\n]+)\)\}=/g, "$1:bind=");
template = template.replace(/\{\$([^}\n]+)\}=/g, "el:$1:from=");
template = template.replace(/\{([^}\n]+)\}=/g, "$1:from=");
template = template.replace(/\(\$([^)\n]+)\)=/g, "el:on:$1=");
template = template.replace(/\(([^)\n]+)\)=/g, "on:$1=");
```

-----

Additional note:
This will change `{(my-happy-value)}=` to `my-happy-value:bind=`
Let me know if I need to also change that. Sounds like it will still work in reading #229 but I could be misinterpreting.

**Comment by phillipskevin** [comment]
Running this on the canjs demos, I found a few edge cases we need to account for before publishing this as a codemod:

1. Need to handle templates created with `stache(...)`. This shouldn't have been changed:
```
-       template: stache("<input value='{{plateName}}' ($input)='update($element.value)'/>"),
+       template: stacheon:"<input value='{{plateName}}' ($input='update($element.value)'/>"),
```

2. we should camelCase properties that are kebab-case. This should have changed `plate-name` to `plateName`:

```
-  <edit-plate {(plate-name)}="editing.licensePlate"/>
+  <edit-plate plate-name:bind="editing.licensePlate"/>
```

**Comment by JaneOri** [comment]
content of `<script type="text/stache">` for `.html` files 

only things inside `stache("...")` for `.js` files

For `.md` files, look html or js codeblocks
\```html
or
\```js

and everything for `.stache` files

Additionally I am transforming the kebab-case to camelCase now

Here's the code transforming 2.3 syntax to context intuitive 3.x binding:
```js

var kebabToCamel = function (kebab) {
  return kebab.replace(/-(.)/g, function (x, $1) {
    return $1.toUpperCase();
  });
};


var transformStache = function (src) {
  src = src.replace(/\{\^\$?([^}\n]+)\}=/g, function (x, $1) {
    return kebabToCamel($1) + ":to=";
  });
  src = src.replace(/\{\(\$?([^)\n]+)\)\}=/g, function (x, $1) {
    return kebabToCamel($1) + ":bind=";
  });
  src = src.replace(/\{\$?([^}\n]+)\}=/g, function (x, $1) {
    return kebabToCamel($1) + ":from=";
  });
  src = src.replace(/\(\$?([^)\n]+)\)=/g, function (x, $1) {
    return "on:" + kebabToCamel($1) + "=";
  });
  
  return src;
};


var transformHtml = function (src) {
  //find script tag with type text/stache
  replace src.replace(/(<script[^>]*type=("|')text\/stache\2[^>]*>)([\s\S]+?)(<\/script>)/g, function (fullStr, $1, quoteType, $3, $4) {
    return $1 + transformStache($3) + $4;
  });
};


var transformJs = function (src) {
  //find call to stache with a template passed in
  //note: only catches the call if a string is passed in and maynot work well if it's not one full string
  replace src.replace(/(\bstache\(\s*(["'`]))((?:[^\\\2]|\\[\s\S])*?)(\2\s*\))/g, function (fullStr, $1, quoteType, $3, $4) {
    return $1 + transformStache($3) + $4;
  });
};


var transformMd = function (src) {
  //find ```html code blocks and treat it as stache
  //find ```js code blocks and treat them as js
  replace src.replace(/(```)(js|html)?((?:[\s\S])+?)\1/g, function (fullStr, ticks, codeBlockType, codeBlock) {
    codeBlockType = codeBlockType || "";
    var output = ticks + codeBlockType;

    if (codeBlockType === "html") {
      output += transformStache(codeBlock);
    } else if (codeBlockType === "js") {
      output += transformJs(codeBlock);
    } else {
      output += codeBlock;
    }
    return output + ticks;
  });
};


module.exports = function transformer(file) {
  var src = file.source;
  var type = file.type;
  
  if (type === "js") {
    src = transformJs(src);
  } else if (type === "md") {
    src = transformMd(src);
  } else if (type === "html") {
    src = transformHtml(src);
  } else if (type === "stache") {
    src = transformStache(src);
  }
  
  return src;
};

```

**Comment by phillipskevin** [comment]
This is working. Awesome work @James0x57.
