### ISSUE TITLE
Add @ operator doc link under the list of binding types to help new users

### ISSUE THREAD

**Issue by JaneOri** [canjs/can-stache-bindings#265]
Though it's not a can-stache-binding, you will often encounter the @ symbol in that area of stache:
`{@set-overlay}="@setOverlay"`

My suggestion is to put it in the list of syntaxes:
<img src="https://user-images.githubusercontent.com/7545075/28930567-feb907b0-7838-11e7-993c-6f0324f62dc8.png" width="200px">

And have it link to a doc that says something along the lines of:
> This is not a can-stache-binding. @ is commonly used to pass functions between a child viewModel and a parent component like so:
> Current syntax: `@set-overlay:from="@setOverlay"` or `@set-overlay:to="@setOverlay"`
> 2.3 syntax: `{@set-overlay}="@setOverlay"` or `{^@set-overlay}="@setOverlay"`
> For more information see [Keys operator @](https://canjs.com/doc/can-stache/keys/at.html)

This is because people will likely look there first trying to find info about it. Especially if they aren't familiar with the underlying structure.

**Comment by justinbmeyer** [comment]
Yeah, while I sympathize with what you are trying to solve, we try to keep our docs related to the module at hand. @ is part of stache. Stache-bindings knows nothing about it. The sidebar is too valuable of real-estate to add any possible other key modifier combination too (*, this, %, ~)
