### ISSUE TITLE
($click) on element with a viewModel causes an error

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#279]
From https://github.com/canjs/can-define/issues/171#issuecomment-322740213 (and https://gitter.im/canjs/canjs?at=59941b57578b44a046b481c5):

>Recently we’re getting this error:
Uncaught TypeError: Cannot define property ($click), object is not extensible
Because we have a ($click) event on a component tag.
>
><my-comp ($click)=“triggerEvent(…)” />
Is that related to this issue?
I can solve it with seal: false, but that doesn't seem right.

**Comment by jeroencornelissen** [comment]
As you asked on gitter:
- can-stache-bindings@3.6.1
- `($click)` throws error but the click still works
- `on:el:click="triggerEvent(...)"` works

**Comment by phillipskevin** [comment]
@jeroencornelissen I'm not able to reproduce this issue with a test or with a sample project.

This is the code I'm using:

```
import DefineMap from 'can-define/map/map';
import stache from 'can-stache';
import Component from 'can-component';

var ParentVM = DefineMap.extend({
    handler() {
        console.log('clicked');
    }
});

var ChildVM = DefineMap.extend({});

Component.extend({
    tag: 'the-parent',
    ViewModel: ParentVM,
    view: stache('<the-child ($click)="handler()" />')
});

Component.extend({
    tag: 'the-child',
    ViewModel: ChildVM,
    view: stache('child')
});

const view = stache('<the-parent />');
document.body.appendChild( view({}) );
```

See anything that is different from your app?

**Comment by jeroencornelissen** [comment]
No, I can't simulate it either.
Our children are build inside a loop and we have some checks, like this example:
http://jsbin.com/fasehevasi/1/edit?html,js,console,output

But that just works.

**Comment by phillipskevin** [comment]
@jeroencornelissen I was able to reproduce the issue with your example. It won't happen in JSBin because the latest can.all doesn't have all the latest packages. Thanks for updating with this. I'll try to get a fix out soon.

**Comment by phillipskevin** [comment]
https://github.com/canjs/can-stache-bindings/releases/tag/v3.6.2 is released with a fix for this if you want to update and try again in your app @jeroencornelissen.
