### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#28]
Not sure if I just released with latest:

http://canjs.github.io/canjs/doc/can-stache-bindings.toChild.html

![canjs_github_io_canjs_doc_can-stache-bindings_tochild_html](https://cloud.githubusercontent.com/assets/78602/17578497/1a02008e-5f4f-11e6-8e4f-ab1669ee908f.png)

That should show the specific available expression types similar to:

![canjs_github_io_canjs_doc_can-stache_expressions_call_html](https://cloud.githubusercontent.com/assets/78602/17578504/32b1560c-5f4f-11e6-9606-34cdb255b9c8.png)

on 

http://canjs.github.io/canjs/doc/can-stache/expressions/call.html

The same goes for the other binding signatures. Thanks!

**Comment by justinbmeyer** [comment]
http://canjs.github.io/canjs/doc/can-stache-bindings.toParent.html could now maybe be used with the converters.

**Comment by matthewp** [comment]
Is that really better? I look at it like Expression is a base class and those are all subclasses, isn't better to link to the expressions page since all are supported?

**Comment by justinbmeyer** [comment]
All are not supported.  Hash expressions don't work.
