### ISSUE TITLE
Add ability to specify whether :to/:from/:bind binds to the viewModel or element

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#280]
These should work:
```
vm:prop:to="val"
vm:prop:from="val"
vm:prop:bind="val"
el:prop:to="val"
el:prop:from="val"
el:prop:bind="val"
```

**Comment by justinbmeyer** [comment]
What are those 2nd ones for? I don't think they are needed.

**Comment by justinbmeyer** [comment]
Like what would 

<my-comp vm:prop:by:obj:to="val">

Do?

By is only useful to event bindings because it changes the binding to the scope.

**Comment by phillipskevin** [comment]
Yeah, you're right. Those don't make sense. I've updated the description.
