### ISSUE TITLE
event starting with 'to', 'from', 'bind', .. not working

### ISSUE THREAD

**Issue by SRoeffaers** [canjs/can-stache-bindings#285]
When I dispatch the trigger 'togglebutton' in my child-component,

`this.dispatch('togglebutton');`

I expect the function 'myfunction' of my parent-component to  be triggered, but it doesn't.
If I change the trigger to 'flipbutton', it does work.. (I think some kind of regex is used. I also tried it with triggers starting with 'to', 'from' and 'bind'..)

`<parent-component >
        <child-component (togglebutton)="myfunction()"/>
</parent-component>`

**Comment by jeroencornelissen** [comment]
Also `on:vm:togglebutton="myfunction()"` won't work.

**Comment by phillipskevin** [comment]
Thanks @Kleppo for alerting us of this and @jeroencornelissen for investigating. We have a release planned for today that enhances how these bindings are parsed. We will make sure this gets fixed along with that.

**Comment by phillipskevin** [comment]
This is fixed in https://github.com/canjs/can-stache-bindings/releases/tag/v3.7.0. Please let us know if you're still seeing issues after upgrading.

**Comment by SRoeffaers** [comment]
Fix works like a charm, Thx! :-)
