### ISSUE TITLE
dataBinding memory leak

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache-bindings#292]
I’m seeing `dataBinding` objects leak in a personal DoneJS app; I’ll update this description once I make a reduced test case.

**Comment by phillipskevin** [comment]
@chasenlehara were you able to reduce this down?

**Comment by chasenlehara** [comment]
Not yet 😞 I will try again after 3.11 is released to see if any of the recent updates fixed it.

**Comment by justinbmeyer** [comment]
@chasenlehara now is a really good time to spot it :-)

**Comment by chasenlehara** [comment]
I started looking into this again over the weekend. It looks like the leak is not here but in one of the SSR/zone packages. I’d like to pair with @matthewp to show him what’s going on and hopefully track it down.
