### ISSUE TITLE
Deprecate old binding syntaxes

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#294]
From https://github.com/canjs/can-stache-bindings/issues/229.

**Comment by bmomberger-bitovi** [comment]
@phillipskevin is this a docs story, a dev warning story, or both?

**Comment by phillipskevin** [comment]
This is primarily a dev warning story, but we can also change "legacy" to be "deprecated" to be more explicit.

![image](https://user-images.githubusercontent.com/5851984/30191911-a616d41a-9409-11e7-9cab-43402b08d85d.png)
