### ISSUE TITLE
input:to can try to write to unwritable properties

### ISSUE THREAD

**Issue by Sinjhin** [canjs/can-stache-bindings#298]
Calling `<input value:to='prop.subprop'/>` or `<input value:to='*prop.subprop'/>` will cause two different but related errors because we try to write to `prop.subprop` when 'prop` may not exist.

This happens in `can-view-scope` line 389
`if(!canReflect.isObservableLike(context) && canReflect.isObservableLike(context[propName]))`
and in the call to `observerReader.write()` above it.

We need to make a helper function like canWriteProperties for line 389 and check `context`.

It would also be better to unify the `observeReader.write()` code to do similar checks that happen below line 389 so that the error always occurs in one place and can be dealt with there.

**Comment by phillipskevin** [comment]
Here is a link to the code for anyone interested: https://github.com/canjs/can-view-scope/blob/69eaa4c3b4870ba72742f10f983429699aad9c25/can-view-scope.js#L389.

So, @Sinjhin you're saying `canReflect.isMapLike(context[propName])` returns `true` for `context['prop']` when it is undefined?

**Comment by Sinjhin** [comment]
No, at this line https://github.com/canjs/can-view-scope/blob/69eaa4c3b4870ba72742f10f983429699aad9c25/can-view-scope.js#L386
If context is null or undefined (which is possible with `<input value:to='prop.subprop'/>` it will not be observableLike but and then try to read `context[prop]` which causes an error.

**Comment by phillipskevin** [comment]
ok, so the fix for this is to change `canReflect.isValueLike(context[propName])` to `context && canReflect.isValueLike(context[propName])` here: https://github.com/canjs/can-view-scope/blob/69eaa4c3b4870ba72742f10f983429699aad9c25/can-view-scope.js#L391.
