### ISSUE TITLE
doc improvements 

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#301]
I think the titles can be improved:

![canjs_-_tochild_from](https://user-images.githubusercontent.com/78602/30356313-f7bb3b6a-97fd-11e7-8756-77e432883c45.png)

The `toChild` in `toChild:from` seems to add "cross" information.  I think these should just be `key:from` or `childKey:from` or `childProp:from`.

**Comment by phillipskevin** [comment]
I think `key:from` or `prop:from` would make sense.

**Comment by mikedane** [comment]
I'm working on updating these docs right now, if you guys can agree on a new name I can implement it. For the record I also like `key:from`.
