### ISSUE TITLE
Support binding scope variables when an event occurs

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#302]
It would be nice if you could send the value of one scope variable to another scope variable when an event occurs.

A use-case for this is updating a prop on `input` and using it to set another `prop` on `change`, like

```html
  <input type="text" value="{{one}}" on:input:value:to="temp">
  <button on:click:temp:by:this:to="one">Update</button>
```

**Comment by justinbmeyer** [comment]
I think this could be done with a way to do setters in the attr value. There is another can-stache issue related to this

**Comment by phillipskevin** [comment]
I'm not sure what you mean by
> setters in the attr value

**Comment by justinbmeyer** [comment]
This issue: https://github.com/canjs/can-stache-bindings/issues/6


```
<input on:enter="name as %element.value"/>
```

**Comment by justinbmeyer** [comment]
@phillipskevin 

What does ` <button on:click:temp:by:this:to="one">Update</button>` do? Sets `one` to `this.temp`?

How about:

```
on:click:scope.temp:to="one"
```

Scope being a reserved word in 4.0.

**Comment by phillipskevin** [comment]
Right, send the value of one scope variable to another scope variable.

Yeah, I like this:
```
on:click:scope.temp:to="one"
```

**Comment by justinbmeyer** [comment]
This is possible now with:

```
on:event:by:scope="otherScope.key = value"
```
