### ISSUE TITLE
3.0: Warn if event handlers are passed Helper Expressions

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#321]
Stache 4.0 is going to drop support for event handlers like:
```
on:click="bar"
```

We should warn in this case in 3.0 so people can change to `on:click="bar()"`.

```
if(!(expr instanceof expression.Call)) {
    warn
}
```

**Comment by rjgotten** [comment]
@phillipskevin 

How are you going to facilitate the case where a custom event is triggered on the view model that carries additional parameters? E.g. (coming from CanJS 2.x) 
```js
can.batch.trigger( this, "customevent", [ some, custom, data ]);
```

Those additional parameters are not surfaced to the expression in an `on:customevent="handler( ... )"` binding based on a call expression. The only way to register a listener that will receive them is to register said listener directly as a function reference with `on:customevent="handler"`, as stache then internally builds up a call expression to which these additional parameters are properly passed along:

https://github.com/canjs/can-stache-bindings/blob/652b1d3a6777d0e73eeabf8b11d778225c65e0ac/can-stache-bindings.js#L474-L480

Without those parameters being surfaced to call expressions inside event-binders, this constitutes a major loss of functionality for me and will mean I will not be able update to 4.0 without a lot of rewrites.

**Comment by phillipskevin** [comment]
@rjgotten, you can use [scope.arguments](https://canjs.com/doc/can-stache/keys/scope.html#scope_arguments), so that your `handler` function gets whatever arguments were used when the event was dispatched.

```
on:customevent="handler(scope.arguments)"
```

**Comment by rjgotten** [comment]
@phillipskevin 

Nice! That's that taken care of then. ^_^

**Comment by justinbmeyer** [comment]
@phillipskevin closed?

**Comment by phillipskevin** [comment]
Yes this is closed, thanks.
