### ISSUE TITLE
on:VIEW_MODEL_OR_DOM_EVENT:value:to='SCOPE_VALUE' docs are wrong

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#337]
The `on:VIEW_MODEL_OR_DOM_EVENT:value:to='SCOPE_VALUE'` signature should be The `on:VIEW_MODEL_OR_DOM_EVENT:KEY:to='SCOPE_VALUE'`

It doesn't have to be `value`, any property or attribute of the element is valid, hence `KEY`.

https://canjs.com/doc/can-stache-bindings.toParent.html#on_VIEW_MODEL_OR_DOM_EVENT_value_to__SCOPE_VALUE_

**Comment by mikedane** [comment]
Fixed in https://github.com/canjs/can-stache-bindings/commit/ed9bb430e5b4ae092c940fc4843e39166d0c9ca7
