### ISSUE TITLE
Register mutation dependencies

### ISSUE THREAD

**Issue by m-mujica** [canjs/can-stache-bindings#345]
- [ ] parent to child
- [ ] child to parent
- [ ] scope
- [ ] viewmodel

I ran into an issue getting scope to work, basically we don't want to register the mutation to the scope itself but its inner context.

Around here:

https://github.com/canjs/can-stache-bindings/blob/c898d015b39ced8fa941ab6cb2269c748a53f091/can-stache-bindings.js#L747-L753

Partial pull request https://github.com/canjs/can-stache-bindings/pull/340

cc: @justinbmeyer

**Comment by m-mujica** [comment]
Update https://github.com/canjs/can-debug/pull/14/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R49 when this is done.

**Comment by justinbmeyer** [comment]
I remember talking about this, did we not figure out a solution? I think Scope is able to figure out what the likely thing to update is. Look at scope’s set method for an example.

**Comment by m-mujica** [comment]
@justinbmeyer we did talk about this quickly before you had a meeting.

You mentioned something about a `setupMutationDependencies` thing; it wasn't clear to me that was _the solution_.

**Comment by justinbmeyer** [comment]
No problem, let’s discuss Monday.
