### ISSUE TITLE
Docs advise using old syntax

### ISSUE THREAD

**Issue by BigAB** [canjs/can-stache-bindings#347]
I noticed [here in the docs](https://canjs.com/doc/can-stache-bindings.toChild.html) we suggest using the old syntax, that should probably be removed right?

<img width="1100" alt="image 2017-11-14 at 12 31 46 pm" src="https://user-images.githubusercontent.com/76821/32797660-18a71aa4-c938-11e7-99a3-43cc1dfeb60a.png">

**Comment by phillipskevin** [comment]
That's not really the old syntax. It's just a magic tag. I copied that note over from the legacy bindings doc: https://canjs.com/doc/can-stache-bindings.legacy-toChild.html.

![image](https://user-images.githubusercontent.com/5851984/32808476-b9a28590-c958-11e7-87a0-0bad6e80cc8a.png)

I assumed that whatever reasoning was behind this message originally was still true, although @justinbmeyer was skeptical of this if I remember correctly.

I think we should leave it in for now until someone has time to do some performance profiling to see if there really isn't a difference.

**Comment by mikedane** [comment]
Hey, I'm working on fixing up these docs right now. If anyone can recommend a way to do the performance profiling I'd be happy to do it

**Comment by phillipskevin** [comment]
I think we should just remove this note. `value:from="foo"` gives good debug info:

![image](https://user-images.githubusercontent.com/5851984/43268939-6c60650a-90b7-11e8-9f5a-8ea294e2d532.png)


...`value="{{ foo }}"` does not:

![image](https://user-images.githubusercontent.com/5851984/43268952-732358ac-90b7-11e8-9af3-18704887f4cc.png)

**Comment by justinbmeyer** [comment]
Both should probably have equally good debug information.  Generally speaking, I prefer `prop:from=` because it doesn't ALWAYS type coerce into a string.  For example: `checked:from="someBoolean"`.

**Comment by justinbmeyer** [comment]
So yeah, remove that warning.

**Comment by mikedane** [comment]
Fixed in #481
