### ISSUE TITLE
Deprecated docs don't show new syntax

### ISSUE THREAD

**Issue by Alfredo-Delgado** [canjs/can-stache-bindings#355]
This might be more of a UX consideration, but it'd save users of the documentation some tedious manual mapping of old => new if deprecated sample code was presented alongside its new counterpart. 

e.g.

```
Deprecated: <my-component ($dom-event)="method('primitive', key, hash1=key1)"/>
Available as of Can 3.(?): <my-component on:dom-event="method('primitive', key, hash1=key1)"/>
```

**Comment by matthewp** [comment]
Alternatively there could be a migration guide/page.

**Comment by phillipskevin** [comment]
Maybe along with this we also mention the codemod: https://canjs.com/doc/guides/upgrade/using-codemods.html#CompleteListofTransformScripts.
