### ISSUE TITLE
Add support for explicitly calling intermediate functions like does().some().thing()

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache-bindings#366]
In 3.0, we support implicitly calling intermediate functions like so: https://github.com/canjs/can-stache-bindings/blob/452312f1c45d6bc986bfc17b4bbcf35eef2a842c/test/bindings-test.js#L1357

However, the explicit version (`does().some().thing()`) does not work.

We should make the explicit version work and add a warning that the implicit version will be removed in 4.0

**Comment by phillipskevin** [comment]
closed by https://github.com/canjs/can-stache-bindings/pull/370.
