### ISSUE TITLE
Too many warnings (false positives)

### ISSUE THREAD

**Issue by jeroencornelissen** [canjs/can-stache-bindings#381]
As discussed in the DoneJS contributers meeting (2017-12-08) video.
We also get a lot false positive warnings. Mostly about attributes set on a component like `role`, `aria-label`, `aria-checked`, `data-key`, ...

As @matthewp said in the [forum](https://forums.donejs.com/t/donejs-contributors-meeting-2017-12-08/777/6):
> The problem is that can-stache-bindings doesn’t distinguish between attributes and viewmodel bindings.

Example warning that can't be fixed:
`WARN: src/mystache:2: role="textbox" is deprecated. Use role:from="'textbox'" instead.`

**Comment by phillipskevin** [comment]
In 4.0, we've removed this deprecated behavior and therefore also removed these warnings.

In order to avoid these false positives in 3.0, I think we would have to keep a list of all valid attributes and not warn for them.

**Comment by matthewp** [comment]
All attribute names are valid attributes, that's the problem. But if this is fixed in 4.0 I think that's good enough.

**Comment by jeroencornelissen** [comment]
It's good enough if it's fixed in 4.0. An extra reason to upgrade asap! 👍

**Comment by matthewp** [comment]
Let's close this then. We should only backport to 3.0 if a lot of people are complaining.
