### ISSUE TITLE
Two-way binding test failing in Edge [4.0]

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache-bindings#390]
This test is failing [in Edge](https://saucelabs.com/beta/tests/d732674961db433d99f5e73fe5d7b180/commands#175) in [this PR](https://github.com/canjs/canjs/pull/3827): https://github.com/canjs/can-stache-bindings/blob/eb62021ebf3897f9c3f8f7d594f655fbebd9f17c/test/colon/element-test.js#L481

**Comment by mindfulmike** [comment]
👍

**Comment by benedmunds** [comment]
🙏

**Comment by chasenlehara** [comment]
I think this was fixed, @mindfulmike @benedmunds if you guys are seeing issues with can-stache-bindings or Edge, could you open a new issue please?
