### ISSUE TITLE
Stache binding within attribute

### ISSUE THREAD

**Issue by eben-roux** [canjs/can-stache-bindings#429]
I have bindings such as `<div class="other-class {{test}}"  />"`.  This seems to still be working but there is a warning in the console: `can-stache/expressions/helper.js: Unable to find helper \"test\"`.

I have created an [example](https://jsbin.com/lifuwoq/edit?html,js,console,output).  The `div` contains the correct output but there is still the warning.  

From the [discussion](https://forums.donejs.com/t/stache-binding-within-attribute/808) in the forum it appears as though the warning may very well be a bug.

**Comment by phillipskevin** [comment]
Issue moved to [canjs/can-stache #477](https://github.com/canjs/can-stache/issues/477) via [**ZenHub**](https://www.zenhub.com/)
