### ISSUE TITLE
Attributes with letters after numbers aren’t bound correctly

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache-bindings#474]
[I’m not sure this is a can-stache-bindings bug, but filing here to start.]

In `can@5.2.2` (and earlier), attributes that end in numbers are bound correctly (e.g. `prop1`) but not with more letters after them (e.g. `prop1A`).

Demo: https://codepen.io/anon/pen/KBwELm?editors=0010

**Comment by cherifGsoul** [comment]
I [Encoded](https://codepen.io/cherifGsoul/pen/XyxoGE?editors=0010) the attribute manually and it works, this is a `can-attribute-encoder` issue

**Comment by cherifGsoul** [comment]
> [I’m not sure this is a can-stache-bindings bug, but filing here to start.]
> 
> In `can@5.2.2` (and earlier), attributes that end in numbers are bound correctly (e.g. `prop1`) but not with more letters after them (e.g. `prop1A`).
> 
> Demo: https://codepen.io/anon/pen/KBwELm?editors=0010

**Comment by cherifGsoul** [comment]
Closing this for https://github.com/canjs/can-stache-bindings/issues/506
