### ISSUE TITLE
Support can-simple-dom ~21

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#48]
Related: https://github.com/canjs/canjs/issues/2185

can-simple-dom doesn't have full DOM support.  So setting something like `.value` won't work.  Instead `.setAttribute()` needs to be called.

Similar to how can-stache's tests work, we should make sure can-stache-bindings can work against the simple dom.

**Comment by matthewp** [comment]
Or can-simple-dom could have a `.value` setter.

**Comment by justinbmeyer** [comment]
@matthewp I've thought about that ... but I think that's untenable.  It would also have to have a `checked` and any other potentially two-way bound property.

**Comment by matthewp** [comment]
This is now tested and passing.
