### ISSUE TITLE
Rich type coercion breaks with bi-directional bindings

### ISSUE THREAD

**Issue by imaustink** [canjs/can-stache-bindings#487]
The following example should render `Austin` twice, once in <my-component> and again in the call to stache near the bottom. However, only the first instance is rendered. Note if you change the value passed into the template to be an instance of `User` rather than a POJO, it works as expected.
```
const User = can.DefineMap.extend({
  name: {
    type: 'string',
    value: 'Austin'
  }
})

can.Component.extend({
  tag: 'my-component',
  view: can.stache(`<p>{{user.name}}</p>`),
  ViewModel: can.DefineMap.extend({
    user: {
      Type: User
    }
  })
})

const template = can.stache(`
  <my-component user:bind="user"></my-component>
  <p>{{user.name}}</p>
`)
const frag = template(new can.DefineMap({
  user: {} // change this to `new User()` and it works
}))

document.body.appendChild(frag)
```

Working codepen for convenience:
https://codepen.io/anon/pen/eLMvBZ?editors=1111

**Comment by chasenlehara** [comment]
@cherifGsoul Would you mind checking to see if this is an issue in CanJS 5 please?

**Comment by cherifGsoul** [comment]
@chasenlehara Yeah CanJS 5 has this issue.
https://codepen.io/cherifGsoul/pen/vMprde?editors=0011
