### ISSUE TITLE
Document how to do old can-value bindings ~21

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#49]
Here: http://canjs.github.io/canjs/doc/can-stache-bindings.html

We should document the old can-value things with the new converters and syntaxes:

https://canjs.com/docs/can.view.bindings.can-value.html

We might need to make an additional converter to handle something like the checkbox with `can-false-value` and such:

```
<input type="checkbox" {($checked)}="boolean-to-value( ~owns.car, "yes", "no" )
```

**Comment by justinbmeyer** [comment]
Kevin's useful gist: https://gist.github.com/phillipskevin/a5892f9f1cf9a4d4ce936beb9080e615

**Comment by justinbmeyer** [comment]
Also figure out how we should solve: https://github.com/canjs/canjs/issues/2368.  Make `$value` work with `<select multiple>`.

Also figure out: https://github.com/canjs/canjs/issues/2369.  Make $value work with opt groups.

**Comment by matthewp** [comment]
## Need:
- [x] - [checkbox](https://canjs.com/docs/can.view.bindings.can-value-checkbox.html)
- [ ] - [radio](https://canjs.com/docs/can.view.bindings.can-value-radio.html)
- [x] - [select](https://canjs.com/docs/can.view.bindings.can-value-select.html)
- [ ] - [select multiple](https://canjs.com/docs/can.view.bindings.can-value-select-multiple.html)
- [x] - checkbox can-value-false (maybe new thing needed)
- [ ] - binding select multiples to a list. ([issue](https://github.com/canjs/canjs/issues/2368))
- [x] - [opt group](https://github.com/canjs/canjs/issues/2369) - behavior is same as select[multiple]

**Comment by matthewp** [comment]
This is being worked on in can-stache-converters now but keeping the issue here.

Radio idea: https://gist.github.com/matthewp/3feeb8ed8bd678c574c8b23c4b3b088c

cc @justinbmeyer

**Comment by matthewp** [comment]
Select multiple idea: https://gist.github.com/matthewp/9a1bf3f292ae063d192d1c01d7d65b4c

This uses boolean-to-inList to bind each `<option>` selected property to a list of items.

**Advantages**
- Reusing boolean-to-inList feels very good.
- No magical properties that aren't real properties.

**Disadvantages**
- More verbose than can-value, but this is true of all converters.

**Comment by matthewp** [comment]
This is done.
