### ISSUE TITLE
scope issue in partials since 4.4.2

### ISSUE THREAD

**Issue by jeroencornelissen** [canjs/can-stache-bindings#491]
Since `can@5.11.1` we're experiencing an issue where a list isn't updated in a partial.

Here is an example:
https://codepen.io/JeroenC82/pen/OBygKo?editors=1011

console warning:
```
The context (list) you passed into thepartial (renderer) is not defined in the scope!
```

**Comment by Mattchewone** [comment]
I have created a new codepen here: https://codepen.io/mattchewone-the-looper/pen/BGqYJZ?editors=0011

This one is using `@5` which will be latest and shows a difference in behaviour between using:
```
{{> partial list }}
``` 
and 
```
{{ partial(list) }}
```
