### ISSUE TITLE
Cannot use a Bracket Expression with :to bindings

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#496]
This works:

```
        <fr-om val:from="obj['from']"></fr-om>
```

...but this:
```
        <t-o val:to="obj['to']"></t-o>
```

Tries to set the literal `"obj['to']"` on the ViewModel instead of parsing the expression.

Here is a codepen: https://codepen.io/kphillips86/pen/pxpBEL?editors=0011.

This should use `expression.parse`:

https://github.com/canjs/can-stache-bindings/blob/d3d342c8dbc0e548480d79a5ba9f8f36bc10b0cf/can-stache-bindings.js#L591-L593

like the other path does:

https://github.com/canjs/can-stache-bindings/blob/d3d342c8dbc0e548480d79a5ba9f8f36bc10b0cf/can-stache-bindings.js#L579-L582

**Comment by justinbmeyer** [comment]
```
<t-o val:to="thing().bar"></t-o>
```

```
<t-o val:to="a[b].c[d].e"></t-o>
```

```
expression = {
  type: "lookup".
  key: "e",
  root: {
    type: "bracket",
    children: [{type: "lookup", key: "d"}],
    root: {.....}
  }
}
```

Hard way

```js
var expressionForObjectWeAreSetting = ast.root
objectSetting = canReflect.getValue( expression.value(scope) );
canReflect.setKeyValue(objectSetting, expression.key, VALUE );
```

Easy way

```
var observable = expression.value(scope);

return observable;


canReflect.setValue(observable, VALUE);
```
