### ISSUE TITLE
Support passing simple setters as functions

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#497]
`<can-crud-modal close:from="this.editingRecord = null">`

`can-crud-modal` is expecting `close` to be a function.  It would be cool if we could see a simple setter and take care of this.

**Comment by chasenlehara** [comment]
@Mattchewone Did https://github.com/canjs/can-stache-bindings/pull/498 address this issue? Can it be closed?

**Comment by Mattchewone** [comment]
@chasenlehara I believe so :)

**Comment by chasenlehara** [comment]
Great, thanks!

FYI GitHub can automatically close issues when PRs are merged if you follow a certain syntax: https://help.github.com/articles/closing-issues-using-keywords/
