### ISSUE TITLE
Should this be considered a cycle?

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#499]
The following test code produces a warning like:

>  can-bind updateValue: attempting to update parent ObservableFromScope<SimpleMap{}.parentValue> to new value: `"gc"`
…but the parent semaphore is at 1 and the child semaphore is at 0. The number of allowed updates is 0.
> The parent value will remain unchanged; it’s currently: `undefined`

The test code looks like the following:

```js
MockComponent.extend({
    tag: "parent-that-gets",
    viewModel: new SimpleMap({
        parentValue: ""
    }),
    template: stache('<child-that-updates child:to="this.parentValue"/>')
});

MockComponent.extend({
    tag: "child-that-updates",
    viewModel: new SimpleMap({
        child: "CHILD"
    }),
    template: stache('<gc-that-updates gc:to="this.child"/>')
});

MockComponent.extend({
    tag: "gc-that-updates",
    viewModel: new SimpleMap({
        gc: "gc"
    })
});

var template = stache("{{# if(this.show) }}<parent-that-gets/>{{/if}}");
var root = new SimpleMap({show: false});
var frag = template(root);
root.set("show", true);
```

Essentially, when `show` turns to true:

1. `<parent-that-gets>` renders `<child-that-updates child:to="this.parentValue"/>`
2. This will update `parentValue` to `"CHILD"`.
3.  Then `<child-that-updates>` will render its template: `<gc-that-updates gc:to="this.child"/>`
4. This will update `child` to `"gc"`, then `child` will try to update `parentValue`.

What should happen here?

## My thoughts

I think these updates should be allowed and not warn.  This is probably a breaking change from `3.0`.

As `can-bind`'s semaphores are primarily used to prevent runaway cycles, and this situation has no cycles, it seems like this is a bug.

I think the easiest fix is that when `can-bind` is one-way, it doesn't prevent cycles.

**Comment by mjstahl** [comment]
I think you are correct about what the easiest fix is. Though I believe there still could be a cycle if you do something like:
```js
A <---- B // PARENT
v       ^
C ----> D // CHILD
```
`B` on `PARENT` sets `A` in a setter which is `from` bound to C on  `CHILD`. `C` sets `D` in a setter which is `to` bound to `B`.  I have not tried this before but if you remove the prevention of cycles from one-way binding, this could be an edge case.

Probably the bigger fix:

> I think these updates should be allowed and not warn. This is probably a breaking change from 3.0.

I do not understand enough of the binding implementation to get why this wouldn't be allowed in the first place, or why it would be a breaking change from 3.0.

**Comment by justinbmeyer** [comment]
@mjstahl, 

> why it would be a breaking change from 3.0

I'm saying that 4.0 is currently different than 3.0.  The change I'm proposing would keep them the same.  4.0 would more closely match 3.0's behavior in this respect.

===========

I think you are thinking of something like:

```
PARENT: {
  view: `<child c:from="a"  d:to:"b"/>`,
  VM: {
    a: "number"
    set b(){  this.a = Math.random() },
  }
}

CHILD: {
  VM: {
    set c(){  this.d = Math.random() },
    d: "number"
  }
}
```

Yes, this would be an edge case that would no longer be prevented.

A different approach might be to try detecting an actual cycle with `queues`.  Currently, we are simply counting how many times something changed with semaphores.  The original problem (lots of updates to a parent) show the problem with simply counting: The parent might change many times, but it's not changing due to a cycle.

What we actually need to do is figure out if we are about to set a value due to changes in this value previously.  If this information was present on a `task`, we could walk up the "stack" and see if value we are about to change was changed on the stack.


While I think using `queues` to solve this problem is the "right" fix. I'm ok turning off cycle detection for one-directional bindings (or increasing to some high number like 100).

**Comment by frank-dspeed** [comment]
@justinbmeyer or we refactor this to streams :) they are able to do backpresure and so on

**Comment by justinbmeyer** [comment]
@frank-dspeed ... if you have a proposal for that, please create in `canjs/canjs`.  Streams have very little to do with this problem.  Even if all of canjs was refactored to use streams instead of it's current observables, cycles could exist and this problem would _still_ need to be addressed.

**Comment by phillipskevin** [comment]
> I think the easiest fix is that when can-bind is one-way, it doesn't prevent cycles.

I think this is a good first fix. I agree that this isn't a cycle and this warning/behavior is confusing.

For anyone that wants to try it, I put this example in a codepen: https://codepen.io/kphillips86/pen/JmKYom?editors=0010.

**Comment by frank-dspeed** [comment]
@justinbmeyer the most easy fix for that cycle is out of my view don't update value if value matches.
on the property lvl

**Comment by mjstahl** [comment]
I have very little experience with cycle detection algorithms but I know a lot of them exist in academia. So I went an looked up some algorithms in hopes that they help for a more long term fix.

I am going to assume that components and their bindings make up a directed graph. Therefore:

http://en.wikipedia.org/wiki/Tarjan%E2%80%99s_strongly_connected_components_algorithm 
http://en.wikipedia.org/wiki/Strongly_connected_components

Also Python's garbage collection is a combination of reference counting  and cycle detection. Below is a link with pointers to source code about how Python does it.

https://stackoverflow.com/a/10962484

**Comment by mjstahl** [comment]
> or increasing to some high number like 100.

I think this is actually more appropriately short term fix, as it also allows for detecting and warning about the edge case I articulated.

**Comment by justinbmeyer** [comment]
@frank-dspeed I'm not sure what you are saying.  Observables already don't "update" if they get a value that matches their value.  

@mjstahl I don't think we need to detect when a cycle is "created", only when a cycle of changes occurs.  This is much easier to figure out.

**Comment by justinbmeyer** [comment]
Closed by: https://github.com/canjs/can-stache-bindings/commit/783688c617417c8a8ef8095ac7521b25dae9b478
