### ISSUE TITLE
Get `enter` out of can-stache-bindings.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#5]
From https://github.com/canjs/canjs/issues/728

We should support things like `($key-escape)`, `($key-right)`, etc.

We do!  Lets show people how to do it by making custom event bindings against https://github.com/canjs/can-util/blob/master/dom/events/events.js.

**Comment by justinbmeyer** [comment]
This should probably be done in can-util.

**Comment by chasenlehara** [comment]
During the UX testing, one of the users was playing around with the TodoMVC app and tried `($escape)` since they saw `($dblclick)` used.
