### ISSUE TITLE
Passing a compute to a component with ~ passes the value ~13

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#50]
From: https://github.com/canjs/canjs/issues/2216

> I'm not sure what two-way binding should do here.  But one way should definitely work.  

I should be able to pass a compute of a scope property to a component with `~`.

``` js
var vm = new can.Map({ foo: 'bar' })
```

``` html
<!-- should pass a compute of 'foo' instead of simply binding 'foo' -->
<foo-bar {compute}="~foo"></foo-bar>
```

http://jsbin.com/diginariwa/edit?html,js,console

I'm not really sure what a 2-way binding would look like or if it should even be possible.

**Comment by matthewp** [comment]
Fixed in https://github.com/canjs/can-stache-bindings/pull/57
