### ISSUE TITLE
on:EVENT:by:KEY throws error when KEY is undefined in scope.

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-stache-bindings#510]
https://jsbin.com/suvusehobu/1/edit

Line 533 in can-stache-bindings.js assumes that the bindingContext will always be set, which is true if it's always an element or view model.  Introducing a scope lookup to find the binding context, as on:EVENT:by:KEY patterns do, breaks this assumption, and the bindingContext may be a nullish value.  When this happens, the binding fails and throws an error.

If bindingContext is not set here, the eventQueue should not be invoked.  Also (I'm unsure whether this is already the case, but should be tested for), the binding should be torn down and set up again when bindingContext changes.

**Comment by justinbmeyer** [comment]
Event binding logic starts here: https://github.com/canjs/can-stache-bindings/blob/dbb288691666502f85cb3924b506b64bda8e7659/can-stache-bindings.js#L404


The `:by:` handling starts here: https://github.com/canjs/can-stache-bindings/blob/dbb288691666502f85cb3924b506b64bda8e7659/can-stache-bindings.js#L456


The hard part about this is that to make this work, we will need to setup a binding on the scope, to see the value changing and re-bind. 

I also think there's a bug (or code that should be improved) by the `byParent.get` call.  That code is assuming the `byParent` has a `.get` method.  This should probably be using `can-stache-key` or `can-key` to read the value.  Even better, this should always be a `new Scope()` so we can get a `ScopeKeyData` object.

I would replace `byParent.get` with something like:

```js
// on:foo:by:subject
scopeKeyData = new Scope( byParent ).computeData("subject")
```

Once you have the `scopeKeyData`, this needs to be listened to for changes:

```js
function updateBinding(newBindingContext, oldBindingContext){
  newBindingContext && canEventQueue.on.call(newBindingContext, event, handler);
  oldBindingContext && canEventQueue.off.call(oldBindingContext, event, handler);
}

canReflect.onValue(scopeKeyData, updateBinding);

// initialize
updateBinding( canReflect.getValue( scopeKeyData) , undefined);
```

`unbindEvent` will need to be updated to teardown the `scopeKeyData` binding:

https://github.com/canjs/can-stache-bindings/blob/dbb288691666502f85cb3924b506b64bda8e7659/can-stache-bindings.js#L518

```js
canReflect.offKeyValue(scopeKeyData, updateBinding);
```


## Other considerations 


can-diff/patcher does very similar stuff ... it's got an observable that can change and it binds to the result of the observable.  I wonder if it's worth extracting this.  I feel like it's other places in CanJS as well ...
