### ISSUE TITLE
Property value setting is not working with VM values

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-stache-bindings#516]
The following does not work:
`<button on:click="this.isOpen = !this.open"> Toggle </button>`

Seems is only working with primitive values, setting the value `this.isOpen` to `true` or `false` works fine.

A CodePen https://codepen.io/cherifGsoul/pen/KYMdma for issue demonstration.

**Comment by chasenlehara** [comment]
[The docs](https://canjs.com/doc/can-stache-bindings.event.html#on_VIEW_MODEL_OR_DOM_EVENT__KEY_VALUE_) don’t mention being able to use `!`. I think this would be a nice feature.

**Comment by cherifGsoul** [comment]
This should be fixed in `can-stache/src/expression.js`

**Comment by cherifGsoul** [comment]
In `can-stache` add `!` to tokens pattern:

https://github.com/canjs/can-stache/blob/83191d3c312845acc70f103d167ef378625284ca/src/expression.js#L37
->
`var tokensRegExp = /('.*?'|".*?"|=|[\w\.\\\-_@\/*%!\$]+|[\(\)]|,|\~|\[|\]\s*|\s*(?=\[))/g`

Update `Lookup`:
https://github.com/canjs/can-stache/blob/83191d3c312845acc70f103d167ef378625284ca/expressions/lookup.js#L11 ->
```js
var Lookup = function(key, root, sourceText) {
	this.inverse = false
	// Read falsy value of the key starts with "!"
	if (key.substring(1, key.length)) {
		this.key = key.slice(1);
		this.inverse = true;
	} else {
		this.key = key;
	}
	this.rootExpr = root;
	canReflect.setKeyValue(this, sourceTextSymbol, sourceText);
};
```
in `can-stache-bindings`:
https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L549 ->
```js
var hashExprs = expr.hashExprs;
var key = Object.keys(hashExprs)[0];
var isInverse = hashExprs[key].inverse;
var value = expr.hashExprs[key].value(runScope);
var isObservableValue = canReflect.isObservableLike(value) && canReflect.isValueLike(value);
var valueToBind;
isObservableValue ? valueToBind = canReflect.getValue(value) : valueToBind = value;
runScope.set(key, isInverse ? !valueToBind : valueToBind);
```

**Comment by cherifGsoul** [comment]
Fixed as https://github.com/canjs/can-stache-bindings/pull/519
