### ISSUE TITLE
6.0: "sticky" bindings broken

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#543]
Sticky bindings (as described here: https://canjs.com/doc/can-stache-bindings.html#StickyBindings) are broken in 6.0.

Changing this: https://github.com/canjs/can-stache-bindings/blob/d217a24acacbe8b7052211e4300a21141be19d40/can-stache-bindings.js#L1090

...back to `"domUI"` fixes the issue, but I don't think this is the correct solution.

Using the `"dom"` queue, the value of the `AttributeObservable` has already changed when [this check](https://github.com/canjs/can-bind/blob/2c0fb26fb15d75a00ec447d3064c17f8ac300ca1/can-bind.js#L540) happens in `can-bind`:

![image](https://user-images.githubusercontent.com/5851984/65921368-a479cc80-e3a7-11e9-9cab-bc4c00caeb10.png)

... where it used to be updated after:
![image](https://user-images.githubusercontent.com/5851984/65921277-69779900-e3a7-11e9-8cbf-585470d0d671.png)

**Comment by justinbmeyer** [comment]
We should be sticking to DOM-hierarchy based queues. domUI is mostly legacy

**Comment by phillipskevin** [comment]
In 6.0, situations like this are working more like a user would expect, so this caveat in the docs no longer applies. With the new queues based on the DOM hierarchy, we are able to handle this correctly, so we're just going to remove the sections from the docs that no longer apply.
