### ISSUE TITLE
bindings map is defined twice

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-stache-bindings#555]
https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L41

This looks like a merge conflict resolution gone wrong.

**Comment by chasenlehara** [comment]
I would double check that JSHint is working… seems like the sort of thing it should catch.

**Comment by bmomberger-bitovi** [comment]
JSHint is running properly, but for whatever reason, it does not catch redeclared variables at that scope.  Contrastingly, if you add `"shadow": "outer"` to the config, it does find some places where we've redeclared vars in inner scopes.
