### ISSUE TITLE
Selects with value=null select options with value=""

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#73]
[This test case](https://github.com/canjs/can-stache-bindings/blob/master/test/bindings-test.js#L1728) fails in IE9/10/Edge.

**Comment by phillipskevin** [comment]
Moved to https://github.com/canjs/can-util/issues/122.

**Comment by phillipskevin** [comment]
This will require a change here once https://github.com/canjs/can-util/issues/122 is fixed.

**Comment by matthewp** [comment]
Fixed by #74
