### ISSUE TITLE
Make memory leak test more consistent

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-stache-bindings#76]
This test fails intermittently:

```
vdom can-value memory leak (#2270) no bindings
```

**Comment by justinbmeyer** [comment]
@bmomberger-bitovi not sure if you created another issue around why we are changing the test.  If not, please use this one. Otherwise, feel free to close this for another one.

**Comment by christopherjbaker** [comment]
@bmomberger-bitovi says Since 3.0.18, the tests pass consistently for bindings.
