### ISSUE TITLE
Cannot use custom event params in can-EVENT callbacks with explicit arguments ~13

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-bindings#9]
From: 
- https://github.com/canjs/canjs/issues/1760
- https://github.com/canjs/canjs/issues/2197

We need some type of spread operator:

```
<input type="text" id="test" ($foobar)="doStuff(%event, ...%args)">
```

**Comment by matthewp** [comment]
@phillipskevin is going to work on a `%arguments`

**Comment by phillipskevin** [comment]
Realized this should be the arguments... not the default arguments.
