### ISSUE TITLE
object[key] binding to child component not updating

### ISSUE THREAD

**Issue by green3g** [canjs/can-stache-bindings#90]
I think I might have found a bug with the {name}="object[key]" binding in can-stache. 
I've been playing around with the new binding syntax, and I think I might have found a bug with the {name}="object[key]" binding in can-stache. It seems that if I change "key", it is not updated in the child property "name" 

I put a bin together: http://jsbin.com/pobolu/edit?html,js,console,output

**Comment by phillipskevin** [comment]
So there were two issues in the JSBin that made it seem like this is not working.

The first was that the `prop` in the `parent` DefineMap was not set up correctly. Originally, it had:

```
  prop: {
    Value: can.DefineMap.extend({
      another: 'another',
      original: 'original',
      changed: 'changed'
    })
  }
```

To make this work, I changed it to:

```
  prop: {
    Value: can.DefineMap.extend({
      another: {
        type: 'string', 
        value: 'another'
      },
      original: {
        type: 'string',
        value: 'original'
      },
      changed: {
        type: 'string',
        value: 'changed'
      }
    })
  }
```

The second issue was that the `<parent-c>` component was creating its own viewModel and not using the object `p` that you're creating and then updating in the setTimeout.

To fix this, I changed:

```
can.Component.extend({
  view: can.stache.from('parent'),
  viewModel: parent,
  tag: 'parent-c'
});
```

to

```
can.Component.extend({
  view: can.stache.from('parent'),
  leakScope: true,
  tag: 'parent-c'
});
```

Here is a JSBin with these two changes: http://jsbin.com/piwoxiciza/edit?html,js,output.

I'm going to close the issue, but feel free to re-open if you still think something is not working correctly.

**Comment by green3g** [comment]
Ah, I missed something obvious there, thanks for taking a look. Also I needed to bind `key` to the `parent-c`'s `key:

```
document.body.appendChild(
  can.stache('<parent-c {key}="key" />')(p)
)
```

**Comment by phillipskevin** [comment]
Yes, you could do it that way instead of removing the `viewModel` and setting `leakScope` on the parent component.
