### ISSUE TITLE
Improve the (event) docs

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-stache-bindings#98]
Link to the current docs: http://canjs.com/doc/can-stache-bindings.event.html

- [ ] The [($DOM_EVENT)='CALL_EXPRESSION'](http://canjs.com/doc/can-stache-bindings.event.html#__DOM_EVENT___CALL_EXPRESSION_) and [(VIEW_MODEL_EVENT)='CALL_EXPRESSION'](http://canjs.com/doc/can-stache-bindings.event.html#_VIEW_MODEL_EVENT___CALL_EXPRESSION_) titles are hard to understand.
- [ ] `($dblclick)` isn’t documented.

**Comment by justinbmeyer** [comment]
I wouldn't expect us to document every dom event. Why dblclick and not mousemove, submit, etc?  Any dom event is valid.

**Comment by chasenlehara** [comment]
I didn’t realize `dblclick` was a DOM event; that’s pretty cool.

It might be useful to mention the common ones in our docs (or at least the ones we mention in our guides), then link to https://www.w3.org/TR/uievents/ for the full list.

**Comment by justinbmeyer** [comment]
> The ($DOM_EVENT)='CALL_EXPRESSION' and (VIEW_MODEL_EVENT)='CALL_EXPRESSION' titles are hard to understand.

Signatures are designed to be precise.  I don't know what would make this more clear and be as accurate.

**Comment by DesignByOnyx** [comment]
If both DOM and VM events are backed by EventEmitter, why not have e a common binding syntax?

**Comment by justinbmeyer** [comment]
You need to know what to bind to. There are cases you want to bind to the element and the vm.  

However, I'm hoping that future versions of can-component can unify this.

**Comment by phillipskevin** [comment]
@chasenlehara is there still work needed to be done here?
